ekf_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    publish_tf: false
    predict_to_current_time: true
    # transform_time_offset: 0.1
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # X,  Y,   Z
    # r,  p,   y,
    # X'',Y',  Z'
    # r', p',  y'
    # X'',Y'', Z''

    odom0: /go2/base/odom
    odom0_config: [true, true, false, 
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom0_differential: false
    odom0_queue_size: 10

    # imu0: imu/data
    # imu0_config: [false, false, false,
    #               false, false, false,
    #               false, false, false,
    #               false, false, true,
    #               true,  true,  false]
    # imu0_differential: false
    # imu0_queue_size: 10
    # imu0_remove_gravitational_acceleration: true