services:
  ros1-bridge:
    image: ros1-bridge:latest
    build:
      context: ./ros1-bridge
      dockerfile: Dockerfile
    container_name: ros1-bridge
    environment:
      ROS_IP: "127.0.0.1"
      ROS_MASTER_URI: "http://127.0.0.1:11311"
    network_mode: host